DROP DATABASE IF EXISTS INMOBILIARIA_BBDD;
CREATE DATABASE INMOBILIARIA_BBDD;
USE INMOBILIARIA_BBDD;

CREATE TABLE CIUDADES
(ID_CIUDAD INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(40) NOT NULL
);

CREATE TABLE TIPOS
(ID_TIPO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
TIPO VARCHAR(30) NOT NULL
);

CREATE TABLE INMUEBLES 
(ID_INMUEBLE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_CIUDAD INT NOT NULL,
ID_TIPO INT NOT NULL,
NUM_HABITACIONES INT,
PRECIO DECIMAL(9,2),
IMAGEN VARCHAR(30),
TAMANIO  INT,
BAÑOS INT,
ESTADO VARCHAR(30),
PLANTA VARCHAR(30),
TERRAZA BOOLEAN,
ASCENSOR BOOLEAN,
FECHA_ALTA DATE,
NOVEDAD BOOLEAN, 
FOREIGN KEY(ID_CIUDAD) REFERENCES CIUDADES(ID_CIUDAD),
FOREIGN KEY(ID_TIPO) REFERENCES TIPOS(ID_TIPO)
);

CREATE TABLE PERFILES
(ID_PERFIL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION VARCHAR(20) NOT NULL
);

CREATE TABLE USUARIOS 
(USERNAME VARCHAR(50) PRIMARY KEY, 
PASSWORD VARCHAR(200) NOT NULL,
ENABLED int,
EMAIL VARCHAR(100)  NOT NULL UNIQUE,
NOMBRE VARCHAR(50), 
APELLIDO VARCHAR(50), 
DIRECCION VARCHAR(100), 
FECHA_ALTA DATE
);

CREATE TABLE USUARIO_PERFILES
(USERNAME VARCHAR(50) NOT NULL,
ID_PERFIL INTEGER NOT NULL,
PRIMARY KEY(USERNAME, ID_PERFIL),
FOREIGN KEY(USERNAME) REFERENCES USUARIOS(USERNAME),
FOREIGN KEY(ID_PERFIL) REFERENCES PERFILES(ID_PERFIL)
);

CREATE TABLE FAVORITOS
(ID_FAVORITOS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_INMUEBLE INT NOT NULL,
USERNAME VARCHAR(50) NOT NULL,
FOREIGN KEY(ID_INMUEBLE) REFERENCES INMUEBLES(ID_INMUEBLE),
FOREIGN KEY(USERNAME) REFERENCES USUARIOS(USERNAME)
);


CREATE USER 'uinmueble'@'localhost' IDENTIFIED BY 'uinmueble';
GRANT ALL PRIVILEGES ON INMOBILIARIA_BBDD.* TO  'uinmueble'@'localhost';

-- DROP USER 'uinmueble'@'localhost' ;